### ISSUE TITLE
Error when using botkit-starter-facebook

### ISSUE THREAD

**Issue by jay-at-avido** [actionably/dashbot#11]
Here's the error I get.

I'm curious why it would call the *addTeamInfo* method at all, looks like some Slack specific thing but I'm not integrating Slack at all, so that is confusing.

```
info: ERROR IN RECEIVE MIDDLEWARE:  TypeError: Cannot convert undefined or null to object
    at addTeamInfo (/home/joao/node-projects/make-me-fat-bot/node_modules/dashbot/src/dashbot.js:169:12)
    at Ware.DashBotSlack.that.receive (/home/joao/node-projects/make-me-fat-bot/node_modules/dashbot/src/dashbot.js:230:25)
    at Ware.<anonymous> (/home/joao/node-projects/make-me-fat-bot/node_modules/wrap-fn/index.js:45:19)
    at next (/home/joao/node-projects/make-me-fat-bot/node_modules/ware/lib/index.js:85:20)
    at Ware.run (/home/joao/node-projects/make-me-fat-bot/node_modules/ware/lib/index.js:88:3)
    at Object.Botkit.botkit.receiveMessage (/home/joao/node-projects/make-me-fat-bot/node_modules/botkit/lib/CoreBot.js:1067:35)
    at Object.Facebookbot.facebook_botkit.handleWebhookPayload (/home/joao/node-projects/make-me-fat-bot/node_modules/botkit/lib/Facebook.js:310:45)
    at /home/joao/node-projects/make-me-fat-bot/components/routes/incoming_webhooks.js:18:20
    at Layer.handle [as handle_request] (/home/joao/node-projects/make-me-fat-bot/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/joao/node-projects/make-me-fat-bot/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/home/joao/node-projects/make-me-fat-bot/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/joao/node-projects/make-me-fat-bot/node_modules/express/lib/router/layer.js:95:5)
    at /home/joao/node-projects/make-me-fat-bot/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/home/joao/node-projects/make-me-fat-bot/node_modules/express/lib/router/index.js:330:12)
    at next (/home/joao/node-projects/make-me-fat-bot/node_modules/express/lib/router/index.js:271:10)
    at serveStatic (/home/joao/node-projects/make-me-fat-bot/node_modules/serve-static/index.js:75:16)
```

**Comment by jhullfly** [comment]
Can you send sample code that you are using to setup the middleware.

Jesse

**Comment by sinned** [comment]
Hey I'm looking at this... it's part of the botkit studio for facebook code:
https://github.com/howdyai/botkit-starter-facebook/issues/1

**Comment by jay-at-avido** [comment]
Added a zip but you will need some facebook credentials and whatnot to test this.

[botkit-test.zip](https://github.com/actionably/dashbot/files/742934/botkit-test.zip)

**Comment by sinned** [comment]
This was a fix in the botkit-studio code, I submitted a pull request here:
https://github.com/howdyai/botkit-starter-facebook/pull/2

**Comment by jay-at-avido** [comment]
It looks like error was in the dashbot integration and according to a commiter has already been fixed on their part:
https://github.com/actionably/dashbot/issues/11
