### ISSUE TITLE
Getting this gRPC error when deploying dashbot to lambda Node 12.x

### ISSUE THREAD

**Issue by TheDreamSaver** [actionably/dashbot#34]
```
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Failed to load gRPC binary module because it was not installed for the current system\nExpected directory: node-v64-linux-x64-glibc\nFound: [node-v57-linux-x64-glibc]\nThis problem can often be fixed by running \"npm rebuild\" on the current system\nOriginal error: Cannot find module '/var/task/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node'",
    "stack": [
        "Runtime.ImportModuleError: Error: Failed to load gRPC binary module because it was not installed for the current system",
        "Expected directory: node-v64-linux-x64-glibc",
        "Found: [node-v57-linux-x64-glibc]",
        "This problem can often be fixed by running \"npm rebuild\" on the current system",
        "Original error: Cannot find module '/var/task/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node'",
        "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
        "    at Object.<anonymous> (/var/runtime/index.js:45:30)",
        "    at Module._compile (internal/modules/cjs/loader.js:778:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)",
        "    at Module.load (internal/modules/cjs/loader.js:653:32)",
        "    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:585:3)",
        "    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)",
        "    at startup (internal/bootstrap/node.js:283:19)"
    ]
}
```

Resolved by using `npm install grpc --target=8.1.0 --target_arch=x64 --target_platform=linux --target_libc=glibc`

and setting lambda runtime to 10.x
but bundle size became too heavy because of the above command.

**Comment by TheDreamSaver** [comment]
I see the bundle size is already too much even with a vanilla install of dashbot.
Is that intended?

**Comment by TheDreamSaver** [comment]
```
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Failed to load gRPC binary module because it was not installed for the current system\nExpected directory: node-v72-linux-x64-glibc\nFound: [node-v64-linux-x64-glibc]\nThis problem can often be fixed by running \"npm rebuild\" on the current system\nOriginal error: Cannot find module '/var/task/node_modules/grpc/src/node/extension_binary/node-v72-linux-x64-glibc/grpc_node.node'\nRequire stack:\n- /var/task/node_modules/grpc/src/grpc_extension.js\n- /var/task/node_modules/grpc/src/client_interceptors.js\n- /var/task/node_modules/grpc/src/client.js\n- /var/task/node_modules/grpc/index.js\n- /var/task/node_modules/google-gax/build/src/grpc.js\n- /var/task/node_modules/google-gax/build/src/index.js\n- /var/task/node_modules/@google-cloud/dlp/src/v2/dlp_service_client.js\n- /var/task/node_modules/@google-cloud/dlp/src/v2/index.js\n- /var/task/node_modules/@google-cloud/dlp/src/index.js\n- /var/task/node_modules/redact-pii/lib/custom/GoogleDLPRedactor.js\n- /var/task/node_modules/redact-pii/lib/index.js\n- /var/task/node_modules/dashbot/src/redactor.js\n- /var/task/node_modules/dashbot/src/make-request.js\n- /var/task/node_modules/dashbot/src/dashbot-facebook.js\n- /var/task/node_modules/dashbot/src/dashbot.js\n- /var/task/index.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
    "stack": [
        "Runtime.ImportModuleError: Error: Failed to load gRPC binary module because it was not installed for the current system",
        "Expected directory: node-v72-linux-x64-glibc",
        "Found: [node-v64-linux-x64-glibc]",
        "This problem can often be fixed by running \"npm rebuild\" on the current system",
        "Original error: Cannot find module '/var/task/node_modules/grpc/src/node/extension_binary/node-v72-linux-x64-glibc/grpc_node.node'",
        "Require stack:",
        "- /var/task/node_modules/grpc/src/grpc_extension.js",
        "- /var/task/node_modules/grpc/src/client_interceptors.js",
        "- /var/task/node_modules/grpc/src/client.js",
        "- /var/task/node_modules/grpc/index.js",
        "- /var/task/node_modules/google-gax/build/src/grpc.js",
        "- /var/task/node_modules/google-gax/build/src/index.js",
        "- /var/task/node_modules/@google-cloud/dlp/src/v2/dlp_service_client.js",
        "- /var/task/node_modules/@google-cloud/dlp/src/v2/index.js",
        "- /var/task/node_modules/@google-cloud/dlp/src/index.js",
        "- /var/task/node_modules/redact-pii/lib/custom/GoogleDLPRedactor.js",
        "- /var/task/node_modules/redact-pii/lib/index.js",
        "- /var/task/node_modules/dashbot/src/redactor.js",
        "- /var/task/node_modules/dashbot/src/make-request.js",
        "- /var/task/node_modules/dashbot/src/dashbot-facebook.js",
        "- /var/task/node_modules/dashbot/src/dashbot.js",
        "- /var/task/index.js",
        "- /var/runtime/UserFunction.js",
        "- /var/runtime/index.js",
        "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
        "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
        "    at Module._compile (internal/modules/cjs/loader.js:956:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)",
        "    at Module.load (internal/modules/cjs/loader.js:812:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:724:14)",
        "    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)",
        "    at internal/main/run_main_module.js:17:11"
    ]
}
```

**Comment by itozapata** [comment]
grpc is a dependency from our use of redact-pii. going to see if i can rework this to be optional in the case you are trying to use dashbot without making use of the redact library. should decrease the size of the inistall

**Comment by TheDreamSaver** [comment]
Yeah if possible please make it optional. Was unaware of this library as well.
Thanks for sharing, it looks good for some future use case.

**Comment by TheDreamSaver** [comment]
Any updates on this @itozapata ?

**Comment by omenocal** [comment]
@TheDreamSaver did you get a solution for this issue? I just run into it and saw you had this issue reported but no one has replied back to you here.

**Comment by TheDreamSaver** [comment]
Hi @omenocal 
I was also using the following command to fix it before deployment on node 12.x:
`npm rebuild --target=12.0.0 --target_platform=linux --target_arch=x64 --target_libc=glibc --update-binary`

I wish there was a way to reduce the package size. Deploying 35-40 MB on every change is a bit of pain if I'm not testing locally.

Also, have you been able to run dashbot on node 14.x on lambda?

**Comment by omenocal** [comment]
@TheDreamSaver I haven't tested it with nodejs 14. For the moment I'll continue with nodejs 12 as I've spent so much time trying to sort this out :/
